### ISSUE TITLE
[index] `printConsoleConfig` (text mode) should print a report of the current selections

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-console#115]
https://github.com/adobe/aio-cli-plugin-console/blob/master/src/commands/console/index.js

It shouldn't log only if the selection is set. So if nothing is set it should be:
```
You are currently in:
1. Org: <no org selected>
2. Project: <no project selected>
3. Workspace: <no workspace selected>
```

**Comment by meryllblanchet** [comment]
@moritzraho could you check?

**Comment by moritzraho** [comment]
taken care of by @rajarju
