### ISSUE TITLE
[workspace:select][workspace:download] command should have cumulative errors

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-console#117]
For a user with no selections, this is the scenario.

Right now, if an org is not selected, it will throw an error (no org selected). A user will fix that and run `workspace:select` or `workspace:download` again, and it will throw an error (no project selected).

The errors should be cumulative, or alternately it can also `printConsoleConfig` as well with this change: #115

**Comment by meryllblanchet** [comment]
@sandeep-paliwal could you check this one?

**Comment by sandeep-paliwal** [comment]
Added PR - https://github.com/adobe/aio-cli-plugin-console/pull/133
