### ISSUE TITLE
[project:select] change error when no org is selected

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-console#118]
For a user with no selections, this is the scenario.

Right now, if an org is not selected, it will throw an error (no org selected). It should print out the error, and call printConsoleConfig as well with this change: #115 (to be consistent with #116)

**Comment by meryllblanchet** [comment]
@rajarju could you have a look?

**Comment by rajarju** [comment]
I think this can be fixed with #115

**Comment by meryllblanchet** [comment]
@rajarju ok, please take #115 in that case. cc @moritzraho
