### ISSUE TITLE
[workspace:download] download location optional arg

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-console#123]
Should we add an optional arg for where to download the file to?

**Comment by meryllblanchet** [comment]
@sandeep-paliwal could you have a look?

**Comment by sandeep-paliwal** [comment]
yup

**Comment by sandeep-paliwal** [comment]
Added PR - https://github.com/adobe/aio-cli-plugin-console/pull/133

**Comment by meryllblanchet** [comment]
Fixed with #133
