### ISSUE TITLE
[index] refer to full namespace of the command

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-console#126]
We've decided (Sarah concurs) to not alias it on the top level; users will have to use the full namespace.

Change these strings:
- from `aio org list` to `aio console:org:list` 
- from `aio org select` to `aio console:org:select`

**Comment by meryllblanchet** [comment]
@rajarju could you update accordingly?

**Comment by moritzraho** [comment]
@purplecabbage already fixed that in https://github.com/adobe/aio-cli-plugin-console/pull/112/commits/6047f62336ae8b3a67c8602fe49ec441daa589dd
