### ISSUE TITLE
Change `list-integrations` command `--passphrase` flag shortcut from `-r` to `-p`

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-console#43]
This is a breaking change. The original shortcut was changed from`-p` to `-r` because of the shortcut to `--page` is `-p`. Now that paging is removed, we can revert to the more intuitive `-p` to be consistent everywhere else the `--passphrase` flag is used.

### Expected Behaviour
`-p` is a shortcut for `--passphrase` for the `console:list-integrations` command.

### Actual Behaviour
`-r` is a shortcut for `--passphrase` for the `console:list-integrations` command.

**Comment by goya** [comment]
i was thinking of bringing back "optional" paging for people with lots of integrations. (like jesse)

we could bring it back without a shortcut so --page --pagesize only

**Comment by shazron** [comment]
@goya Can you file another issue to discuss bring this back? Preparing the next release's Release Notes and guidance, which had this feature out, so if this is to be put back in, I'd need to know now.

**Comment by goya** [comment]
yep.
